python/dify_plugin/interfaces/model/large_language_model.py
ParameterType.TEXT is used for `json_schema` field.  
Now use this feature will raise error:
0.15 repo's [code](https://github.com/langgenius/dify/blob/989fb11fd715a96576333207189a12d8594c60f1/api/core/model_runtime/model_providers/__base/large_language_model.py#L866)
=> fix ParameterType.TEXT is not supported

python/dify_plugin/invocations/file.py
Fixed `UploadFileResponse` to be correctly initialized from `response` value.
https://github.com/langgenius/dify-plugin-sdks/blob/e764cd2d9e0225b9ac4f27d3e486ed0578b47a46/python/dify_plugin/invocations/file.py#L66-L70
=> fix: UploadFileResponse to support optional type initialization from mime_type

python/dify_plugin/entities/model/__init__.py
when a llm's config use `use_template`,  it's label will display incorrect:
After fix:
=> label display error when use_template

python/dify_plugin/invocations/model/llm.py
when we define a tool's params with `model-selector` type,  and use it this way:
```
response = self.session.model.llm.invoke(
model_config=tool_parameters.get('model'),
prompt_messages=prompt_messages,
stream=False
)
```
It will raise error:
```
Traceback (most recent call last):
File "d:\database\.venv\Lib\site-packages\dify_plugin\core\server\io_server.py", line 92, in _execute_request_in_thread
self._execute_request(
File "d:\database\.venv\Lib\site-packages\dify_plugin\plugin.py", line 327, in _execute_request
for message in response:
File "d:\database\.venv\Lib\site-packages\dify_plugin\core\plugin_executor.py", line 76, in invoke_tool
yield from tool.invoke(request.tool_parameters)
File "D:\database\tools\query.py", line 65, in _invoke
response = self.session.model.llm.invoke( …
```
=> fix invoke llm raise error

python/dify_plugin/interfaces/model/large_language_model.py, python/dify_plugin/interfaces/model/openai_compatible/llm.py
migrate this PR https://github.com/langgenius/dify/pull/13392
Currently, many models rely on `dify_plugin==0.0.1b65`, which utilizes a hardcoded `<details ...>` tag to handle reason content. This approach needs to be replaced.
=> migrate the <think> tag

python/dify_plugin/interfaces/agent/__init__.py
[dify-plugin-tod_agent#1](https://github.com/svcvit/dify-plugin-tod_agent/issues/1)
[#14562](https://github.com/langgenius/dify/issues/14562)
[#14904](https://github.com/langgenius/dify/issues/14904)
[#15830](https://github.com/langgenius/dify/issues/15830)
set the default value of entity in the `AgentModelConfig` class to None.
Thanks to [HamaWhiteGG](https://github.com/svcvit/dify-plugin-tod_agent/issues/1#issuecomment-2721520006) for the solution.
=> Fix the error in running the agent plugin

python/dify_plugin/interfaces/agent/__init__.py, python/dify_plugin/invocations/model/llm.py
Added support for calling blocking model methods from within plugins to enable non-streaming Function Call invocations. The related PRs are as follows:
https://github.com/langgenius/dify/pull/15732
=> feat: add llm blocking invoke

python/dify_plugin/interfaces/model/openai_compatible/llm.py
fix:Let OAICompatLargeLanguageModel compatible with the ​"data:" format for streaming response messages 
related issues:https://github.com/langgenius/dify/issues/15486
=> fix:Let OAICompatLargeLanguageModel compatible with the ​"data:" format for streaming response messages

python/dify_plugin/interfaces/model/large_language_model.py
This is regression of #8451, and re-application of #9148 by @hjlarry.
Related issues and PRs:
- https://github.com/langgenius/dify-official-plugins/issues/477
- https://github.com/langgenius/dify-official-plugins/issues/425
- https://github.com/langgenius/dify/issues/14475
- https://github.com/langgenius/dify-plugin-sdks/issues/28
- https://github.com/langgenius/dify-plugin-sdks/pull/29
In the current implementation, `self._code_block_mode_wrapper` is executed when the `response_format` is `json_schema`, but this method is intended to force output format to `JSON` or `XML` that is independently implemented by Dify itself, and not for the Structured Output feature that the LLM model possesses.
When this method is called when the `response_format` is neither `JSON` nor `XML` such as …
=> fix: bypass _code_block_mode_wrapper if response_format is not JSON or XML

python/.ruff.toml
Prohibit calls to `breakpoint()` in committed code.
=> feat(python): Introduct flake8-debugger (T10) ruleset with ruff

python/.ruff.toml, python/dify_plugin/core/runtime.py, python/dify_plugin/core/server/__base/filter_reader.py, python/dify_plugin/core/server/__base/request_reader.py, python/dify_plugin/core/server/io_server.py, python/dify_plugin/core/server/router.py, python/dify_plugin/interfaces/model/openai_compatible/llm.py, python/dify_plugin/plugin.py
Introduce the flake8-builtins (A) ruleset to prevent accidental shadowing of Python's built-in functions.
Address existing issues primarily by adding `# noqa` to suppress warnings where necessary.
=> feat(python): Integrate flake8-builtins (A) ruleset with ruff

python/dify_plugin/entities/model/message.py, python/tests/test_tool_call_model_init.py
Certain OpenAI-compatible LLM providers (e.g., SGLang, SiliconFlow) may return explicit `None` values in tool call response fields when operating in streaming mode.
To prevent Pydantic validation errors, ensure that string fields in ToolCall instances default to empty string (`""`) during initialization.
=> Fix: handle explicit None values in ToolCall responses from OpenAI-compatible LLMs

python/dify_plugin/core/server/__base/request_reader.py, python/dify_plugin/core/server/serverless/request_reader.py, python/dify_plugin/core/server/stdio/request_reader.py, python/dify_plugin/core/server/tcp/request_reader.py
In the RequestReader class, the lock and readers variables are defined as class variables shared by all instances, causing lock contention and high CPU usage issues in high-concurrency scenarios.
1. Converted class variables to instance variables to ensure each RequestReader instance has its own lock and readers list
2. Added super().__init__() calls in subclasses to properly initialize instance variables
3. Optimized lock usage by reducing lock holding time during filter operations
4. Added error handling in the event loop to prevent high CPU usage during exceptions
This fix resolves the CPU 100% usage and system deadlock issues that occurred in high-concurrency scenarios.
- python/dify_plugin/core/server/__base/request_reader.py
- …
=> Fix: Convert shared class variables to instance variables to solve lock contention and CPU issues

python/dify_plugin/entities/model/llm.py, python/dify_plugin/entities/model/message.py, python/dify_plugin/interfaces/model/large_language_model.py, python/dify_plugin/interfaces/model/openai_compatible/llm.py, python/dify_plugin/invocations/model/llm.py, python/examples/agent/output_parser/cot_output_parser.py, python/examples/jina/models/text_embedding/text_embedding.py, python/examples/openai/models/llm/llm.py, python/tests/test_llm_result.py, python/tests/test_tool_call_model_init.py
Solves high CPU usage of dify-api container caused by LLMResultChunk decoding
Related: 
- https://github.com/langgenius/dify/issues/17799
- https://github.com/langgenius/dify-official-plugins/issues/648
=> enhancement: remove prompt_messages from LLMResult and LLMResultChunk

python/dify_plugin/invocations/storage.py, python/tests/invocations/test_storage.py
Replace generic `Exception` raises with `NotFoundError` when the key is missing,
and `StorageInvocationError` for other response errors. This improves error
handling at call sites by avoiding overly generic exceptions.
Add correspond tests for exception raising logic.
=> feat(python): Add specific error classes for StorageInvocation

python/dify_plugin/interfaces/model/openai_compatible/llm.py, python/tests/interfaces/model/openai_compatible/test_increase_tool_call.py
1. Identify new tool call instances using `tool_call_id` when available.
2. For model providers that are not fully compatible with OpenAI's schema (returning only `function_name` instead of `tool_call_id`), fallback to generating random `tool_call_id` for each new tool call.
Ref PR in main repo: [#17781](https://github.com/langgenius/dify/pull/17781)
=> fix: incorrectly uses new_tool_call.function.name while getting existing tool calls

python/dify_plugin/core/entities/plugin/setup.py, python/tests/entities/plugin/test_declaration.py
- Changed minimum_dify_version from required to optional in PluginConfiguration.
- Added unit tests to verify behavior when minimum_dify_version is not provided.
=> fix: update minimum_dify_version to be optional in PluginConfiguration

.github/workflows/mkdocs.yaml
- Changed permissions for contents from read to write to allow for documentation deployment.
=> chore: update GitHub Actions permissions in mkdocs workflow

python/dify_plugin/core/server/tcp/request_reader.py
In debug mode, thread locks block responses and heartbeats, causing TCP to reconnect.
fixes #98 
> [!IMPORTANT]
> Please review the checklist below before submitting your pull request.:
=> fix: In debug mode, thread locks block responses and heartbeats, causing TCP to reconnect.

python/dify_plugin/entities/tool.py, python/dify_plugin/interfaces/tool/__init__.py
Add type `list` to JsonMessage. Now `Tool.create_json_message` can return a `list`.
```python
class JsonMessage(BaseModel):
json_object: Mapping | list
def to_dict(self):
return {"json_object": self.json_object}
```
Example:
Note that corresponding support needs to be added simultaneously in [https://github.com/langgenius/dify](https://github.com/langgenius/dify)
Relevent PR in Dify: [#19026](https://github.com/langgenius/dify/pull/19026)
=> feat: support list in JsonMessage

python/dify_plugin/entities/endpoint.py, python/tests/entities/endpoint/test_endpoint_group.py
- Introduced a class method `_load_yaml_file` to encapsulate YAML file loading logic.
- Enhanced the `validate_endpoints` method to support both direct endpoint configurations and YAML file paths.
- Added unit tests for loading endpoint configurations from YAML strings and files.
=> feat(endpoint): support declare endpoints in groups

python/dify_plugin/core/server/stdio/request_reader.py, python/tests/servers/test_stdio.py
This (probably) resolves the issues that had been widely reported regarding high CPU usage and increased processing times with multimodal input.
There's still probably room for further speed improvements, such as by changing how JSON serialization is handled, but for now, I'm submitting this PR to address the main cause.
- https://github.com/langgenius/dify/issues/17799
- https://github.com/langgenius/dify/issues/19052
- closes https://github.com/langgenius/dify/issues/16441
- closes https://github.com/langgenius/dify-official-plugins/issues/757
- closes https://github.com/langgenius/dify-official-plugins/issues/779
- and more
There are mainly two major issues with the current implementation, both related to the `request_reader`:
- L24: It only receives up to 512 bytes at a time from …
=> fix: improve buffer handling for multimodal input

python/dify_plugin/interfaces/agent/__init__.py, python/dify_plugin/interfaces/endpoint/__init__.py, python/dify_plugin/interfaces/model/ai_model.py, python/dify_plugin/interfaces/tool/__init__.py
- Added `@final` decorator to the constructors of `AgentStrategy`, `Endpoint`, `AIModel`, and `Tool` classes to prevent overriding.
- Included documentation notes in each constructor to indicate that they should not be overridden.
=>  chore: mark constructors as final in multiple classes

python/dify_plugin/core/entities/plugin/setup.py
- Introduced an optional `repo` field in the `PluginConfiguration` class to store the repository URL of the plugin, enhancing the configuration capabilities.
=> feat: add repository URL field to manifest

python/dify_plugin/config/config.py, python/dify_plugin/plugin.py
- Currently, we have to manually separate the URL from the page into host and port fields.
- It's handy to support REMOTE_INSTALL_URL copied in the plugin SDK.
=> feat: support REMOTE_INSTALL_URL config for remote installing and debugging

python/dify_plugin/interfaces/model/openai_compatible/llm.py
add response body to CredentialsValidateFailedError exceptions to aid in error diagnosis, especially useful for Third-party model service deployment.
=> fix[0.4.0]: add response body to CredentialsValidateFailedError exceptions to aid in error diagnosis, especially useful for locally provided models

python/dify_plugin/entities/provider_config.py
- add `bool` to ProviderConfig.default
related PR: https://github.com/langgenius/dify/pull/23282
Thank you for your contribution! Before submitting your PR, please make sure you have completed the following checks:
=> fix: type for ProviderConfig.default
